language: python
python:
  - "3.3"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libhdhomerun-dev
  - find . -name '*.pyc' -delete
install:
  - python setup.py install
script: py.test
